# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 657686c912648c3d8b0ef8c8656ec0946dcd7877b0323489724f761456256c17201b340823dafe258958b98314638a5d37d6512b6c7efb74183451e067bd476c

test:
  secret_key_base: 740b193534228cea34f18d9b7f6dec2c7f2745e08ac963ee0fc24b1e5224a2db8a38eef0e189750e4ecf476c40246caebc8ae44280aed15bd530e42527dbea6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
